ALTER TABLE camion_model
    ALTER COLUMN id TYPE VARCHAR(36),
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE tarifa_model
    ALTER COLUMN id TYPE VARCHAR(36),
    ALTER COLUMN id DROP DEFAULT;

ALTER TABLE deposito_model
    ALTER COLUMN id TYPE VARCHAR(36),
    ALTER COLUMN id DROP DEFAULT;

DROP SEQUENCE IF EXISTS camion_model_id_seq;
DROP SEQUENCE IF EXISTS tarifa_model_id_seq;
DROP SEQUENCE IF EXISTS deposito_model_id_seq;
